### ISSUE TITLE
Add Lessons Schema + `/api/getLessons` API Endpoint

### ISSUE THREAD

**Issue by guypy** [guypy/sawa_project#31]
**Add Lesson Schema**
- Under /src/models/ we need a `Lesson.js` file. A schema defines the model that will be in the database. You can take a look at `/src/models/User.js` for reference.
- The fields we need should be according to `src/components/Lessons/stub-data/lessons.json`.
- Notice that the `faculty` should be defined as an enum, take a look at User.js for reference.
- `day` should also be an enum. You define a new enum in `src/models/enums.js`.

**Lessons API**
You will need to create an API endpoint that will retrieve all the lessons in the database.
How to do it:
- You should add a new file `/src/server/api/lessons.js`, it should look similar to `/src/server/api/users.js`.
- Create a static method that will retrieve all the lessons from the database and return it to the user.
- To get the lessons something like this should work: `Lesson.find({}, (err, lessons) => {...}`. Take a look at mongoose documentation.
- To send the data back to the user use `res.send(lessons)`.

**Comment by amjadegbaria** [comment]
done
